//
// Generated file, do not edit! Created by nedtool 5.4 from Student.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __STUDENT_M_H
#define __STUDENT_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Student.msg:1</tt> by nedtool.
 * <pre>
 * packet Student
 * {
 *     simtime_t totalAnswerTime;
 *     int questionNumber;
 * }
 * </pre>
 */
class Student : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::simtime_t totalAnswerTime;
    int questionNumber;

  private:
    void copy(const Student& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Student&);

  public:
    Student(const char *name=nullptr, short kind=0);
    Student(const Student& other);
    virtual ~Student();
    Student& operator=(const Student& other);
    virtual Student *dup() const override {return new Student(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual ::omnetpp::simtime_t getTotalAnswerTime() const;
    virtual void setTotalAnswerTime(::omnetpp::simtime_t totalAnswerTime);
    virtual int getQuestionNumber() const;
    virtual void setQuestionNumber(int questionNumber);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Student& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Student& obj) {obj.parsimUnpack(b);}


#endif // ifndef __STUDENT_M_H

